name: update-music

on:
  schedule:
    - cron: '0 * * * *'  # ë§¤ ì‹œê°„ ì •ê°
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run music script
        run: python get_music.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add README.md daily_song.json
          git commit -m "ğŸµ ìŒì•… ì¶”ì²œ ì—…ë°ì´íŠ¸" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main


# name: update-music

# on:
#   schedule:
#     - cron: '0 * * * *'  # ë§¤ ì‹œê°„ ì‹¤í–‰
#   workflow_dispatch:

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: pip install requests

#       - name: Run music script
#         run: python get_music.py

#       - name: Commit and push
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"
#           git add README.md
#           git commit -m "ğŸµ ìŒì•… ì¶”ì²œ ì—…ë°ì´íŠ¸" || echo "No changes to commit"
#           git push

